**Student Marks problem**
Problem (Real Life)

You are given marks of 5 students in 3 subjects:

Math

Physics

CS

You must:

Store data using NumPy

Analyze performance

Filter students

Modify data

Use slicing, masking, aggregation, broadcasting



**Data storing**

In [4]:
import numpy as np
marks=np.array([
    [85, 78, 92],   # Student 1
    [60, 55, 65],   # Student 2
    [90, 88, 95],   # Student 3
    [45, 50, 40],   # Student 4
    [72, 68, 70]    # Student 5
])
"""
         CS  Math  Physics
student1 [85, 78,   92],
student2 [60, 55,   65],
student3 [90, 88,   95],
student4 [45, 50,   40],
student5 [72, 68,   70]

"""
print(marks)

[[85 78 92]
 [60 55 65]
 [90 88 95]
 [45 50 40]
 [72 68 70]]


**Basic Info**

In [5]:
print(marks.shape)#Students,Subjects
print(marks.size)#Total elements
print(marks.dtype)#Array data type

(5, 3)
15
int64


**Average marks per student**

In [6]:
avg_students=np.mean(marks,axis=1)
print(avg_students)
for i,avg in enumerate(avg_students):
  print(f"Average marks of student{i+1}:{avg}")

[85. 60. 91. 45. 70.]
Average marks of student1:85.0
Average marks of student2:60.0
Average marks of student3:91.0
Average marks of student4:45.0
Average marks of student5:70.0


**Average marks per subject**

In [7]:
avg_students1=np.mean(marks,axis=0)
print(avg_students1)
for i,avg in enumerate(avg_students1):
  if i==0:
    print(f"Average of marks in CS:{avg}")
  elif i==1:
    print(f"Average of marks in Math:{avg}")
  else:
    print(f"Average of marks in Physics:{avg}")

[70.4 67.8 72.4]
Average of marks in CS:70.4
Average of marks in Math:67.8
Average of marks in Physics:72.4


**Top Students**

In [8]:
top_students=avg_students>=80#Boolean Masking
print(top_students)
print(marks[top_students])

[ True False  True False False]
[[85 78 92]
 [90 88 95]]


In [9]:
print(avg_students)

[85. 60. 91. 45. 70.]


**Weaker Students**

In [10]:
weaker_student=avg_students<=60#Boolean Masking
print(weaker_student)
print(marks[weaker_student])

[False  True False  True False]
[[60 55 65]
 [45 50 40]]


**Grace Marks**

In [11]:
marks=marks+5
print(marks)

[[ 90  83  97]
 [ 65  60  70]
 [ 95  93 100]
 [ 50  55  45]
 [ 77  73  75]]


In [12]:
marks[marks>100]=100
print(marks)

[[ 90  83  97]
 [ 65  60  70]
 [ 95  93 100]
 [ 50  55  45]
 [ 77  73  75]]





**Analyzing CS marks with slicing**



In [13]:
cs_marks=marks[:,0]
print(cs_marks)

[90 65 95 50 77]


**Math marks of first 3 students**

In [14]:
math_marks=marks[:3,1]
print(math_marks)

[83 60 93]


**Physics marks of first 4 students**

In [15]:
phy_marks=marks[:4,2]
print(phy_marks)

[ 97  70 100  45]


**Overall Analysis**

In [16]:
print(f"Maximum marks:{np.max(marks)}")
print(f"Mainimum marks:{np.min(marks)}")
print(f"Class average:{np.mean(marks)}")

Maximum marks:100
Mainimum marks:45
Class average:75.2


In [18]:
print(marks)

[[ 90  83  97]
 [ 65  60  70]
 [ 95  93 100]
 [ 50  55  45]
 [ 77  73  75]]


In [21]:
pass_mask=np.all(marks>=50,axis=1)
fail_mask=np.any(marks<50,axis=1)
pass_students=marks[pass_mask]
fail_students=marks[fail_mask]
print(f"pass_students:{pass_students}")
print(f"fail_students:{fail_students}")

pass_students:[[ 90  83  97]
 [ 65  60  70]
 [ 95  93 100]
 [ 77  73  75]]
fail_students:[[50 55 45]]


In [36]:
avg_students=np.mean(marks,axis=1)
grades=[]
#print(avg_students)
for i,avg in enumerate(avg_students):
  #print(f"Average marks of student{i+1}:{avg}")
  if avg>=80:
    grades.append(f"student{i}->Grade A")
  elif avg>=70 and avg<=84:
    grades.append(f"student{i}->Grade B")
  elif avg>=60 and avg<=69:
    grades.append(f"student{i}->Grade C")
  elif avg<60:
    grades.append(f"student{i}->Grade D")
  else:
    grades.append(f"student{i}->Grade F")
print(grades)


['student0->Grade A', 'student1->Grade C', 'student2->Grade A', 'student3->Grade D', 'student4->Grade B']


In [40]:
avg_per_subject=np.mean(marks,axis=0)
print(avg_per_subject)
#[CS->75.4,Math->72.8,Physics77.4]
for i,avg in enumerate(avg_per_subject):
  lowest_avg=np.argmin(avg_per_subject)
if lowest_avg==0:
  print("CS is the toughest subject.")
elif lowest_avg==1:
  print("Math is the toughest subject.")
else:
  print("Physics is the toughest subject.")

[75.4 72.8 77.4]
Math is the toughest subject.
